from __future__ import annotations

from typing import Protocol

from korea_stock_mcp.models import DisclosureItem, FinancialMetric, PriceBar, SecurityProfile


class MarketDataAdapter(Protocol):
    async def search_security(self, query: str) -> list[SecurityProfile]: ...
    async def get_security_profile(self, ticker: str) -> SecurityProfile | None: ...
    async def get_price_history(self, ticker: str, limit: int = 60) -> list[PriceBar]: ...
    async def get_financial_metrics(self, ticker: str) -> list[FinancialMetric]: ...
    async def get_recent_disclosures(self, ticker: str, limit: int = 20) -> list[DisclosureItem]: ...
